services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    hostname: mysql
    networks:
      - discord-tickets
    volumes:
      - tickets-mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tickets
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} # change this to a secure password
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # change this to a (different) secure password
      MYSQL_USER: tickets

  bot:
    build: .
    depends_on:
      - mysql
    restart: unless-stopped
    hostname: bot
    networks:
      - discord-tickets
    ports:
      - 8169:8169
    volumes:
      - tickets-bot:/home/container/user
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    tty: true
    stdin_open: true
    # Please refer to the documentation:
    # https://discordtickets.app/self-hosting/configuration/#environment-variables
    environment:
      DB_CONNECTION_URL: ${DB_CONNECTION_URL} # change `insecure` to the MYSQL_PASSWORD you set above
      DISABLE_ENCRYPTION: ${DISABLE_ENCRYPTION}
      DISCORD_SECRET: ${DISCORD_SECRET} # required
      DISCORD_TOKEN: ${DISCORD_TOKEN} # required
      ENCRYPTION_KEY: ${ENCRYPTION_KEY} # required
      DB_PROVIDER: ${DB_PROVIDER}
      HTTP_EXTERNAL: ${HTTP_EXTERNAL} # change this to your server's external IP (or domain)
      HTTP_HOST: 0.0.0.0
      HTTP_INTERNAL:
      HTTP_PORT: 8169
      HTTP_TRUST_PROXY: ${HTTP_TRUST_PROXY} # set to true if you're using a reverse proxy
      INVALIDATE_TOKENS:
      OVERRIDE_ARCHIVE: null
      PUBLIC_BOT: "false"
      PUBLISH_COMMANDS: "false"
      SUPER: 362627839339790336 # optionally add `,youruseridhere`

networks:
  discord-tickets:

volumes:
  tickets-mysql:
  tickets-bot:
