name: discord-tickets

services:
  mysql:
    container_name: discord-tickets-mysql
    image: mysql:8
    restart: unless-stopped
    hostname: mysql
    networks:
      - discord-tickets
    volumes:
      - ${DISCORD_TICKETS_DATA_DIR}/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tickets
      MYSQL_USER: tickets
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  bot:
    container_name: discord-tickets-bot
    build: .
    depends_on:
      - mysql
    restart: unless-stopped
    hostname: bot
    networks:
      - discord-tickets
    ports:
      - "8169:8169"
    user: "1000:1000"
    volumes:
      - ${DISCORD_TICKETS_DATA_DIR}/bot:/home/container/user
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    tty: true
    stdin_open: true
    environment:
      DB_PROVIDER: mysql
      DB_CONNECTION_URL: "mysql://tickets:${MYSQL_PASSWORD}@mysql:3306/tickets"
      DISCORD_SECRET: ${DISCORD_SECRET}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      DISABLE_ENCRYPTION: ${DISABLE_ENCRYPTION}
      HTTP_EXTERNAL: ${HTTP_EXTERNAL}
      HTTP_HOST: 0.0.0.0
      HTTP_INTERNAL: ""
      HTTP_PORT: 8169
      HTTP_TRUST_PROXY: ${HTTP_TRUST_PROXY}
      PUBLIC_BOT: "false"
      PUBLISH_COMMANDS: "false"
      SUPER: "362627839339790336"


networks:
  discord-tickets:
