logs:
  files:
    directory: ./logs
    enabled: true
    keepFor: 30
  level: info
presence:
  activities:
    - name: "Need help? ğŸŸï¸"
      type: 3
    - name: "Â¿Necesitas ayuda? ğŸŸï¸"
      type: 3
  interval: 20
  status: online
stats: true
templates:
  transcript: transcript.md
updates: true
